# Generated by Django 2.2.25 on 2021-12-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='format',
            field=models.CharField(max_length=10),
        ),
    ]
